config/routes.rb
Rails.application.routes.draw do
  resources :sweeps

   root 'sweeps#index'

end

app/models/sweep.rb
class Sweep < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sweeps_controller.rb
class SweepsController < ApplicationController
  before_action :set_sweep, only: [:show, :edit, :update, :destroy]

  # GET /sweeps
  # GET /sweeps.json
  def index
    @sweeps = Sweep.all
  end

  # GET /sweeps/1
  # GET /sweeps/1.json
  def show
  end

  # GET /sweeps/new
  def new
    @sweep = Sweep.new
  end

  # GET /sweeps/1/edit
  def edit
  end

  # POST /sweeps
  # POST /sweeps.json
  def create
    @sweep = Sweep.new(sweep_params)

    respond_to do |format|
      if @sweep.save
        format.html { redirect_to @sweep, notice: 'Sweep was successfully created.' }
        format.json { render :show, status: :created, location: @sweep }
      else
        format.html { render :new }
        format.json { render json: @sweep.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sweeps/1
  # PATCH/PUT /sweeps/1.json
  def update
    respond_to do |format|
      if @sweep.update(sweep_params)
        format.html { redirect_to @sweep, notice: 'Sweep was successfully updated.' }
        format.json { render :show, status: :ok, location: @sweep }
      else
        format.html { render :edit }
        format.json { render json: @sweep.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sweeps/1
  # DELETE /sweeps/1.json
  def destroy
    @sweep.destroy
    respond_to do |format|
      format.html { redirect_to sweeps_url, notice: 'Sweep was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sweep
      @sweep = Sweep.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sweep_params
      params.require(:sweep).permit(:title, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sweeps_helper.rb
module SweepsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sweepkeeper</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sweeps/_form.html.erb
<%= form_for(@sweep) do |f| %>
  <% if @sweep.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sweep.errors.count, "error") %> prohibited this sweep from being saved:</h2>

      <ul>
      <% @sweep.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sweeps/edit.html.erb
<h1>Editing sweep</h1>

<%= render 'form' %>

<%= link_to 'Show', @sweep %> |
<%= link_to 'Back', sweeps_path %>

app/views/sweeps/index.html.erb
<h1>All sweeps</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sweeps.each do |sweep| %>
      <tr>
        <td><%= sweep.title %></td>
        <td><%= sweep.date %></td>
        <td><%= link_to 'Show', sweep %></td>
        <td><%= link_to 'Edit', edit_sweep_path(sweep) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sweep', new_sweep_path %>

app/views/sweeps/new.html.erb
<h1>New sweep</h1>

<%= render 'form' %>

<%= link_to 'Back', sweeps_path %>

app/views/sweeps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @sweep.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @sweep.date %>
</p>

<%= link_to 'Edit', edit_sweep_path(@sweep) %> |
<%= link_to 'Back', sweeps_path %>